version: "3"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./
    env_file: ./.env
    restart: unless-stopped
    volumes:
      - './files:/uploads'
      - './:/project'
