version: "3"
services:
  server:
    build:
      dockerfile: ./deployment/Dockerfile
      context: ./
    env_file: ./deployment/.env
    restart: unless-stopped
    volumes:
      - './files:/uploads'
      - './:/project'
